name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:

  build:
    name:  Static checks
    runs-on: ubuntu-18.04


    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    # Runs a set of commands using the runners shell
    - name: Install Dependencies
      run: npm install
